name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Check if maintainer
        continue-on-error: true
        env:
          GITHUB_PR_USER: ${{ github.actor }}
        run: |
          source env.sh;
          if [ "$GITHUB_PR_USER" != "$REPO_USERNAME"]; then
            echo "Github PR user was $GITHUB_PR_USER, not maintainer $REPO_USERNAME, so will not auto merge PR";
            exit 1;
          fi;
          echo "Github PR user was maintainer $REPO_USERNAME, will auto merge PR";
      - name: automerge
        if: success()
        uses: "pascalgn/automerge-action@2c8e667a3386187418587517e5bfe33470d19b5b"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"