name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  # TODO: status may be triggering automerge unexpectedly
  #
  # Automerge pipeline got started for a regular commit on master "on: status" even though
  # status here is empty. Perhaps this is old syntax and just need to remove status.
  status: {}
jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Install dependencies
        run: |
          pipenv sync
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pipenv run pytest --cov=./ --cov-report=xml
      - name: Static Typing Checks with mypy
        run: |
          pipenv run mypy $(python name.py)
  automerge:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Check if maintainer
        continue-on-error: true
        env:
          GITHUB_PR_USER: ${{ github.actor }}
        run: |
          python is_maintainer.py
      # TODO [#16]: no auto merge label stops auto PR merge
      #
      # Currently the automerge workflow will merge any PR by maintainers. Need a "no auto merge" label to prevent
      # this from happening when a maintainer wants other contributors to review the PR.
      - name: automerge
        if: success()
        uses: "pascalgn/automerge-action@2c8e667a3386187418587517e5bfe33470d19b5b"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "!no auto merge"