name: 2nd Try For Update Template using Cruft

on:
  schedule:
    - cron: '43 * * * *'  # every day at 3:00 AM
#    - cron: "0 3 * * *"  # every day at 3:00 AM

jobs:
  templateUpdate:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
      ref: master
